export const HomeRouteURL : string = '/'
export const HomeDataURL : string = '/api/home'
export const SiteInfoURL : string = '/api/site'
export const ContactDataURL : string = '/api/contact'
export const ResumeDataURL : string = '/api/resume'
